modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_github_link}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_github_link}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = 'mod_icon.png'

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "modern_industrialization"
type = "required"
versionRange = "${mi_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kubejs"
type = "optional"
versionRange = "${kubejs_version_range}"
ordering = "AFTER"
side = "BOTH"